http:
  routers:
    homeassistant:
      rule: Host(`home.{{ env "DOMAIN" }}`)
      service: homeassistant
      entryPoints:
        - web
      middlewares:
        - public-chain
  services:
    homeassistant:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8123"
