http:
  middlewares:

    gzip:
      compress: {}
    
    redirect-to-https:
      redirectScheme:
        scheme: https

    security-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        referrerPolicy: "same-origin"
    
    traefik-auth:
      basicAuth:
        users:
          - '{{ env "SVC_DASHBOARD_HASH" }}'
    
    public-chain:
      chain:
        middlewares:
          - gzip
          - security-headers
          - redirect-to-https
      
    authentik-chain:
      chain:
        middlewares:
          - gzip
          - security-headers
          - authentik
    
    streaming-chain:
      chain:
        middlewares:
          - redirect-to-https
          - security-headers

    infra-chain:
      chain:
        middlewares:
          - gzip
          - security-headers
          - traefik-auth
