http:
  middlewares:
    public-chain:
      chain:
        middlewares:
          - gzip
          - security-headers
          - redirect-to-https
      
    authentik-chain:
      chain:
        middlewares:
          - gzip
          - security-headers
          - authentik
    
    streaming-chain:
      chain:
        middlewares:
          - redirect-to-https
          - security-headers

    infra-chain:
      chain:
        middlewares:
          - gzip
          - security-headers
          - traefik-auth
