services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    env_file:
      - .env
    user: ${UID}:${GID} # should be owner of volumes
    restart: unless-stopped
    volumes:
      - "${SVC_STORAGE_DIR}:/data"
      - "${MUSIC_DIR}:/music:ro"
      - "./navidrome.toml:/navidrome.toml:ro"
    environment:
      ND_MUSICFOLDER: /music
      ND_DATAFOLDER: /data
      ND_CONFIGFILE: /navidrome.toml
      ND_EXTAUTH_TRUSTEDSOURCES: 172.16.0.0/12
      ND_EXTAUTH_USERHEADER: X-authentik-username
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.navidrome.rule=Host(`music.${DOMAIN}`)"
      - "traefik.http.routers.navidrome.entrypoints=web"
      - "traefik.http.routers.navidrome.middlewares=authentik-streaming-chain@file"
      - "traefik.http.services.navidrome.loadBalancer.server.port=4533"

networks:
  traefik:
    external: true
