# Pihole Compose File
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
# Capabilities notes: https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2025.03.0
    networks:
      - frontend
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5353:443/tcp"
    env_file:
      - .env
    environment:
      TZ: 'America/Los_Angeles'
      FTLCONF_webserver_api_password: ${WEBPASSWORD}
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - './etc-pihole:/etc/pihole'
    restart: unless-stopped

networks:
  frontend:
    external: true
