# Traefik Setup
services:
  traefik:
    image: traefik:v3.6.12
    container_name: traefik
    restart: always
    env_file:
      - .env
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./conf:/etc/traefik/conf:ro # Extra directory for dynamic configurations

networks:
  traefik:
    name: traefik
    driver: bridge
