services:
  grafana:
    container_name: grafana
    image: docker.io/grafana/grafana-oss:latest
    restart: unless-stopped
    env_file:
      - .env
    user: ${GRAFANA_USER_ID:-1000}:${GRAFANA_GROUP_ID:-1000}
    environment:
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=postgres
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=${GRAFANA_DB_USER}
      - GF_DATABASE_PASSWORD=${GRAFANA_DB_PASSWORD}
      - GF_DATABASE_SSL_MODE=disable
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_NAME=grafana
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=${GRAFANA_OAUTH_CLIENT_ID}
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=${GRAFANA_OAUTH_CLIENT_SECRET}
      - GF_AUTH_GENERIC_OAUTH_SCOPES=openid profile email groups
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://auth.${DOMAIN}/application/o/authorize/
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://auth.${DOMAIN}/application/o/token/
      - GF_AUTH_GENERIC_OAUTH_API_URL=https://auth.${DOMAIN}/application/o/userinfo/
      - GF_AUTH_SIGNOUT_REDIRECT_URL=https://auth.${DOMAIN}/application/o/grafana/end-session/
      - GF_AUTH_OAUTH_AUTO_LOGIN=true
      - GF_SERVER_ROOT_URL=https://grafana.${DOMAIN}
      - GF_AUTH_OAUTH_ALLOW_INSECURE_EMAIL_LOOKUP=true
      - GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH=${GRAFANA_OAUTH_ROLE_ATTRIBUTE_PATH:-"'Viewer'"}
    networks:
      - postgres
      - traefik
    volumes:
      - ${SVC_STORAGE_DIR}:/var/lib/grafana
    labels:
      - traefik.enable=true
      - traefik.http.services.grafana.loadBalancer.server.port=3000
      - traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN}`)
      - traefik.http.routers.grafana.entrypoints=web
      - traefik.http.routers.grafana.middlewares=public-chain@file

networks:
  traefik:
    external: true
  postgres:
    external: true
