services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    env_file: .env
    environment:
      - JELLYFIN_PublishedServerUrl=https://media.${DOMAIN}
    networks:
      - traefik
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ${SVC_CONFIG_DIR}:/config
      - ${SVC_CACHE_DIR}:/cache
      - type: bind
        source: ${SVC_MEDIA_STORAGE}
        target: /media
        read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`media.${DOMAIN}`)"
      - "traefik.http.routers.jellyfin.entrypoints=web"
      - "traefik.http.routers.jellyfin.middlewares=streaming-chain@file"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    restart: 'unless-stopped'

networks:
  traefik:
    external: true
