services:
  app:
    build: ./app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      # Database Config
      MYSQL_HOST: db
      # Redis Config
      REDIS_HOST: redis
      # Apache Config
      OVERWRITE_PROTOCOL: "https"
      # Nextcloud Config
      NEXTCLOUD_DATA_DIR: /var/www/html/data
      NEXTCLOUD_TRUSTED_DOMAINS: "cloud.${DOMAIN}"
    volumes:
      - ${NEXTCLOUD_STORAGE}:/var/www/html
    networks:
      - frontend
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.${DOMAIN}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
    restart: unless-stopped

  db:
    image: mariadb:10.6
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    restart: unless-stopped

  redis:
    image: redis:alpine
    networks:
      - backend
    restart: unless-stopped

  cron:
    image: nextcloud:latest
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ${NEXTCLOUD_STORAGE}:/var/www/html
    networks:
      - backend
    restart: unless-stopped

volumes:
  db_data:

networks:
  frontend:
    external: true
  backend:
    internal: true
