---
services:
  syncthing:
    image: syncthing/syncthing:2.0.15
    container_name: syncthing
    hostname: homelab-syncthing
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${SVC_CONFIG_DIR}:/var/syncthing
      - ${SVC_VAULTS_DIR}:/srv/vaults
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing.rule=Host(`syncthing.${DOMAIN}`)"
      - "traefik.http.routers.syncthing.entrypoints=web"
      - "traefik.http.routers.syncthing.middlewares=public-chain@file"
      - "traefik.http.services.syncthing.loadBalancer.server.port=8384"
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3

networks:
  traefik:
    external: true
