services:
  server:
    container_name: authentik-server
    image: ghcr.io/goauthentik/server:2026.2.1
    restart: unless-stopped
    command: server
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
      AUTHENTIK_POSTGRESQL__HOST: host.docker.internal
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__USER: ${POSTGRES_USER}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${SVC_STORAGE_DIR}/media:/media
      - ${SVC_STORAGE_DIR}/custom-templates:/templates
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authentik.rule=Host(`auth.${DOMAIN}`)"
      - "traefik.http.routers.authentik.entrypoints=web"
      - "traefik.http.routers.authentik.middlewares=public-chain@file"
      - "traefik.http.services.authentik.loadBalancer.server.port=9000"
    networks:
      - backend
      - traefik
  worker:
    image: ghcr.io/goauthentik/server:2026.2.1
    container_name: authentik-worker
    restart: unless-stopped
    command: worker
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
      AUTHENTIK_POSTGRESQL__HOST: host.docker.internal
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__USER: ${POSTGRES_USER}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${POSTGRES_PASSWORD}
      AUTHENTIK_REVERSE_PROXY: "true"

    # `user: root` and the docker socket volume are optional.
    # See more for the docker socket integration here:
    # https://goauthentik.io/docs/outposts/integrations/docker
    # Removing `user: root` also prevents the worker from fixing the permissions
    # on the mounted folders, so when removing this make sure the folders have the correct UID/GID
    # (1000:1000 by default)
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${SVC_STORAGE_DIR}/media:/media
      - ${SVC_STORAGE_DIR}/certs:/certs
      - ${SVC_STORAGE_DIR}/custom-templates:/templates
    networks:
      - backend

networks:
  traefik:
    external: true
  backend:
    name: authentik_backend
    driver: bridge
