services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    user: ${UID:-1000}:${GID:-1000}
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.external-url=http://prometheus.internal
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ${SVC_PROMETHEUS_DIR}:/prometheus
    networks:
      - traefik
      - backend
    labels:
      - traefik.enable=true
      - traefik.http.services.prometheus.loadBalancer.server.port=9090
      - traefik.http.routers.prometheus.rule=Host(`prometheus.internal`)
      - traefik.http.routers.prometheus.entrypoints=web
      - traefik.http.routers.prometheus.middlewares=infra-chain@file
    depends_on:
      - node_exporter
      - cadvisor
  
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    networks:
      - backend
    volumes: 
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    privileged: true
    devices: 
      - "/dev/kmsg"
  
  node_exporter:
    container_name: node_exporter
    image: prom/node-exporter:latest
    restart: always
    user: ${UID:-1000}:${GID:-1000}
    command:
      - --path.rootfs=/host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro
    networks:
      - backend
    
  grafana:
    container_name: grafana
    image: docker.io/grafana/grafana-oss:latest
    restart: unless-stopped
    user: ${UID:-1000}:${GID:-1000}
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=host.docker.internal
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=${GRAFANA_DB_USER}
      - GF_DATABASE_PASSWORD=${GRAFANA_DB_PASSWORD}
      - GF_DATABASE_SSL_MODE=disable
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_NAME=grafana
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=${GRAFANA_OAUTH_CLIENT_ID}
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=${GRAFANA_OAUTH_CLIENT_SECRET}
      - GF_AUTH_GENERIC_OAUTH_SCOPES=openid profile email groups
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://auth.${DOMAIN}/application/o/authorize/
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://auth.${DOMAIN}/application/o/token/
      - GF_AUTH_GENERIC_OAUTH_API_URL=https://auth.${DOMAIN}/application/o/userinfo/
      - GF_AUTH_SIGNOUT_REDIRECT_URL=https://auth.${DOMAIN}/application/o/grafana/end-session/
      - GF_AUTH_OAUTH_AUTO_LOGIN=true
      - GF_SERVER_ROOT_URL=https://grafana.${DOMAIN}
      - GF_AUTH_OAUTH_ALLOW_INSECURE_EMAIL_LOOKUP=true
      - GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH=${GRAFANA_OAUTH_ROLE_ATTRIBUTE_PATH:-"'Viewer'"}
    networks:
      - backend
      - postgres
      - traefik
    volumes:
      - ${SVC_GRAFANA_DIR}:/var/lib/grafana
    labels:
      - traefik.enable=true
      - traefik.http.services.grafana.loadBalancer.server.port=3000
      - traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN}`)
      - traefik.http.routers.grafana.entrypoints=web
      - traefik.http.routers.grafana.middlewares=public-chain@file
    depends_on:
      - prometheus

networks:
  backend:
    driver: bridge
  traefik:
    external: true
