services:
  actual-server:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actual-server
    env_file: .env
    environment:
      ACTUAL_DATA_DIR: /data
      ACTUAL_LOGIN_METHOD: openid
      ACTUAL_ALLOWED_LOGIN_METHODS: openid
      ACTUAL_OPENID_SERVER_HOSTNAME: https://actual.${DOMAIN}
    volumes:
      # Change './actual-data' below to the path to the folder you want Actual to store its data in on your server.
      # '/data' is the path Actual will look for its files in by default, so leave that as-is.
      - ${SVC_STORAGE_DIR}:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.actual-server.rule=Host(`actual.${DOMAIN}`)"
      - "traefik.http.routers.actual-server.entrypoints=web"
      - "traefik.http.routers.actual-server.middlewares=public-chain@file"
      - "traefik.http.services.actual-server.loadbalancer.server.port=5006"
    healthcheck:
      # Enable health check for the instance
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    networks:
      - traefik

networks:
  traefik:
    external: true
