# Traefik static configuration file
entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      trustedIPs:
        - 172.16.0.0/12
  metrics:
    address: ":8082"

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true

api:
  dashboard: true

log:
  level: INFO

accessLog:
  filters:
    statusCodes:
      - "400-599"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik

  file:
    directory: /etc/traefik/conf/
    watch: true
